"""
Error code constants for API error handling
"""


class ErrorCode:
    """Standardized error codes for API responses"""

    # General errors (1xxx)
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    BAD_REQUEST = "BAD_REQUEST"

    # Neo blockchain errors (2xxx)
    NEO_RPC_TIMEOUT = "NEO_RPC_TIMEOUT"
    NEO_RPC_ERROR = "NEO_RPC_ERROR"
    NEO_INVALID_ADDRESS = "NEO_INVALID_ADDRESS"
    NEO_INVALID_TRANSACTION = "NEO_INVALID_TRANSACTION"
    NEO_INSUFFICIENT_BALANCE = "NEO_INSUFFICIENT_BALANCE"
    NEO_CONTRACT_ERROR = "NEO_CONTRACT_ERROR"

    # SpoonOS errors (3xxx)
    SPOONOS_AGENT_ERROR = "SPOONOS_AGENT_ERROR"
    SPOONOS_TOOL_ERROR = "SPOONOS_TOOL_ERROR"
    SPOONOS_WORKFLOW_ERROR = "SPOONOS_WORKFLOW_ERROR"

    # Workflow errors (4xxx)
    WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
    WORKFLOW_EXECUTION_ERROR = "WORKFLOW_EXECUTION_ERROR"
    WORKFLOW_VALIDATION_ERROR = "WORKFLOW_VALIDATION_ERROR"

    # Payment errors (5xxx)
    X402_PAYMENT_REQUIRED = "X402_PAYMENT_REQUIRED"
    X402_PAYMENT_INVALID = "X402_PAYMENT_INVALID"
    X402_PAYMENT_EXPIRED = "X402_PAYMENT_EXPIRED"
